# Generated by Django 4.0.4 on 2022-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_evento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
